// Generated by gencpp from file mymessage/Message1.msg
// DO NOT EDIT!


#ifndef MYMESSAGE_MESSAGE_MESSAGE1_H
#define MYMESSAGE_MESSAGE_MESSAGE1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mymessage
{
template <class ContainerAllocator>
struct Message1_
{
  typedef Message1_<ContainerAllocator> Type;

  Message1_()
    : text()
    , number(0)  {
    }
  Message1_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::mymessage::Message1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mymessage::Message1_<ContainerAllocator> const> ConstPtr;

}; // struct Message1_

typedef ::mymessage::Message1_<std::allocator<void> > Message1;

typedef boost::shared_ptr< ::mymessage::Message1 > Message1Ptr;
typedef boost::shared_ptr< ::mymessage::Message1 const> Message1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mymessage::Message1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mymessage::Message1_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mymessage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mymessage': ['/home/ax/Code/ROS_projects/msg_create/src/mymessage/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mymessage::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mymessage::Message1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mymessage::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mymessage::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mymessage::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mymessage::Message1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mymessage::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ae3591edb22917b11846d84bc548557";
  }

  static const char* value(const ::mymessage::Message1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ae3591edb22917bULL;
  static const uint64_t static_value2 = 0x11846d84bc548557ULL;
};

template<class ContainerAllocator>
struct DataType< ::mymessage::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mymessage/Message1";
  }

  static const char* value(const ::mymessage::Message1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mymessage::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n\
int32 number\n\
";
  }

  static const char* value(const ::mymessage::Message1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mymessage::Message1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mymessage::Message1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mymessage::Message1_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYMESSAGE_MESSAGE_MESSAGE1_H
