// Generated by gencpp from file node_service/my_serviceRequest.msg
// DO NOT EDIT!


#ifndef NODE_SERVICE_MESSAGE_MY_SERVICEREQUEST_H
#define NODE_SERVICE_MESSAGE_MY_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_service
{
template <class ContainerAllocator>
struct my_serviceRequest_
{
  typedef my_serviceRequest_<ContainerAllocator> Type;

  my_serviceRequest_()
    : one()
    , two()  {
    }
  my_serviceRequest_(const ContainerAllocator& _alloc)
    : one(_alloc)
    , two(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _one_type;
  _one_type one;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _two_type;
  _two_type two;





  typedef boost::shared_ptr< ::node_service::my_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_service::my_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct my_serviceRequest_

typedef ::node_service::my_serviceRequest_<std::allocator<void> > my_serviceRequest;

typedef boost::shared_ptr< ::node_service::my_serviceRequest > my_serviceRequestPtr;
typedef boost::shared_ptr< ::node_service::my_serviceRequest const> my_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_service::my_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_service::my_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_service::my_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_service::my_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_service::my_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_service::my_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_service::my_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_service::my_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_service::my_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b0a810fadb8285286476efec58f7b6a";
  }

  static const char* value(const ::node_service::my_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b0a810fadb82852ULL;
  static const uint64_t static_value2 = 0x86476efec58f7b6aULL;
};

template<class ContainerAllocator>
struct DataType< ::node_service::my_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_service/my_serviceRequest";
  }

  static const char* value(const ::node_service::my_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_service::my_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string one\n\
string two\n\
";
  }

  static const char* value(const ::node_service::my_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_service::my_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.one);
      stream.next(m.two);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_service::my_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_service::my_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "one: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.one);
    s << indent << "two: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.two);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_SERVICE_MESSAGE_MY_SERVICEREQUEST_H
