// Generated by gencpp from file my_service/AddInts.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ADDINTS_H
#define MY_SERVICE_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <my_service/AddIntsRequest.h>
#include <my_service/AddIntsResponse.h>


namespace my_service
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace my_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_service::AddInts > {
  static const char* value()
  {
    return "85a734c776d49ce7e013b15b395d3f69";
  }

  static const char* value(const ::my_service::AddInts&) { return value(); }
};

template<>
struct DataType< ::my_service::AddInts > {
  static const char* value()
  {
    return "my_service/AddInts";
  }

  static const char* value(const ::my_service::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_service::AddIntsRequest> should match 
// service_traits::MD5Sum< ::my_service::AddInts > 
template<>
struct MD5Sum< ::my_service::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_service::AddInts >::value();
  }
  static const char* value(const ::my_service::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_service::AddIntsRequest> should match 
// service_traits::DataType< ::my_service::AddInts > 
template<>
struct DataType< ::my_service::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_service::AddInts >::value();
  }
  static const char* value(const ::my_service::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_service::AddIntsResponse> should match 
// service_traits::MD5Sum< ::my_service::AddInts > 
template<>
struct MD5Sum< ::my_service::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_service::AddInts >::value();
  }
  static const char* value(const ::my_service::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_service::AddIntsResponse> should match 
// service_traits::DataType< ::my_service::AddInts > 
template<>
struct DataType< ::my_service::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_service::AddInts >::value();
  }
  static const char* value(const ::my_service::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ADDINTS_H
