// Generated by gencpp from file my_service/AddIntsRequest.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ADDINTSREQUEST_H
#define MY_SERVICE_MESSAGE_ADDINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct AddIntsRequest_
{
  typedef AddIntsRequest_<ContainerAllocator> Type;

  AddIntsRequest_()
    : first(0)
    , second(0)  {
    }
  AddIntsRequest_(const ContainerAllocator& _alloc)
    : first(0)
    , second(0)  {
  (void)_alloc;
    }



   typedef int32_t _first_type;
  _first_type first;

   typedef int32_t _second_type;
  _second_type second;





  typedef boost::shared_ptr< ::my_service::AddIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::AddIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddIntsRequest_

typedef ::my_service::AddIntsRequest_<std::allocator<void> > AddIntsRequest;

typedef boost::shared_ptr< ::my_service::AddIntsRequest > AddIntsRequestPtr;
typedef boost::shared_ptr< ::my_service::AddIntsRequest const> AddIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::AddIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::AddIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05577f62131ad26921bff0de6b2cb722";
  }

  static const char* value(const ::my_service::AddIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05577f62131ad269ULL;
  static const uint64_t static_value2 = 0x21bff0de6b2cb722ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/AddIntsRequest";
  }

  static const char* value(const ::my_service::AddIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 first\n\
int32 second\n\
";
  }

  static const char* value(const ::my_service::AddIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::AddIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::AddIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<int32_t>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<int32_t>::stream(s, indent + "  ", v.second);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ADDINTSREQUEST_H
